# Generated by Django 5.2.5 on 2025-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_rename_inventorychange_inventory_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='product',
        ),
    ]
