# Generated by Django 5.2.5 on 2025-09-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
